# Generated by Django 3.2.4 on 2021-07-07 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_investments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investments',
            name='plan',
        ),
        migrations.AddField(
            model_name='investments',
            name='plan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='investments', to='main.plan'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='investments',
            name='user',
        ),
        migrations.AddField(
            model_name='investments',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='investments', to='auth.user'),
            preserve_default=False,
        ),
    ]
