# Generated by Django 3.2.4 on 2021-07-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210707_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='status',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
    ]
