# Generated by Django 3.2.4 on 2021-07-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planname', models.CharField(max_length=10)),
                ('dividend', models.DecimalField(decimal_places=2, max_digits=11)),
                ('roi', models.IntegerField()),
                ('min_deposit', models.IntegerField()),
                ('max_deposit', models.IntegerField()),
                ('plan_image', models.FileField(upload_to='plans')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runningdays', models.CharField(max_length=10)),
                ('totalinvestments', models.DecimalField(decimal_places=2, max_digits=11)),
                ('revenupaid', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
    ]
