# Generated by Django 3.2.4 on 2021-07-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentby', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('review', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('commend_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
